version: 0.0
os: linux
files:
  - source: .
    destination: /opt/porttrack/app
permissions:
  - object: /opt/porttrack/app
    pattern: "**"
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/deps.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/healthcheck.sh
      timeout: 60
      runas: root
