name: deploy-porttrack

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    # una cola por ambiente
    concurrency:
      group: deploy-porttrack-${{ matrix.env }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        env: [dev, stgtest, prod]

    environment: ${{ matrix.env }}
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      APP_NAME: porttrack-app
      S3_BUCKET: porttrack-artifacts
      KEY_PREFIX: ${{ matrix.env }}
      ZIP_NAME: artifact-${{ github.sha }}.zip
      SHA_NAME: artifact-${{ github.sha }}.sha256

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps & (skip) tests
        working-directory: app
        run: |
          npm ci --no-audit --no-fund || npm install
          echo "No tests, skipping"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::885812046449:role/ga-deploy-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.run_id }}

      # ---- Slack: INICIO ----
      - name: Slack | Inicio deploy
        if: always()
        continue-on-error: true
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          payload=$(jq -n \
            --arg env "${{ matrix.env }}" \
            --arg actor "${GITHUB_ACTOR}" \
            --arg repo "${GITHUB_REPOSITORY}" \
            --arg sha "$SHORT_SHA" \
            '{text: ":rocket: *Inicio deploy* `\($env)` por *\($actor)*",
              attachments:[{color:"#439FE0",
                fields:[
                  {title:"Repo",value:$repo,short:true},
                  {title:"Commit",value:$sha,short:true}
                ]}]}')
          curl -fsS -X POST -H 'Content-type: application/json' \
            --data "$payload" "$SLACK_WEBHOOK_URL" >/dev/null

      - name: Ensure scripts are executable
        run: chmod +x scripts/*.sh || true

      - name: Package artifact
        run: |
          zip -r "${ZIP_NAME}" . \
            -x ".git/*" ".github/*" "app/node_modules/*" \
               "**/*.env" "**/*.pem" "**/*.key" "**/id_rsa" "**/id_ed25519"
          shasum -a 256 "${ZIP_NAME}" > "${SHA_NAME}"

      - name: Upload artifact to S3 (SSE-S3)
        run: |
          aws s3 cp "${ZIP_NAME}" "s3://${S3_BUCKET}/${KEY_PREFIX}/${ZIP_NAME}" --sse AES256
          aws s3 cp "${SHA_NAME}" "s3://${S3_BUCKET}/${KEY_PREFIX}/${SHA_NAME}" --sse AES256

      - name: Register App Revision
        run: |
          aws deploy register-application-revision \
            --application-name "${APP_NAME}" \
            --s3-location bucket="${S3_BUCKET}",key="${KEY_PREFIX}/${ZIP_NAME}",bundleType=zip

      - id: create_deploy
        name: Create Deployment (Rolling / In-place)
        run: |
          DEPLOY_ID=$(aws deploy create-deployment \
            --application-name "${APP_NAME}" \
            --deployment-group-name "dg-${{ matrix.env }}" \
            --revision "revisionType=S3,s3Location={bucket=${S3_BUCKET},key=${KEY_PREFIX}/${ZIP_NAME},bundleType=zip}" \
            --query deploymentId --output text)
          echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_OUTPUT
          echo "DEPLOY_URL=https://${AWS_REGION}.console.aws.amazon.com/codesuite/codedeploy/deployments/${DEPLOY_ID}?region=${AWS_REGION}" >> $GITHUB_OUTPUT
          echo "Deployment creado: $DEPLOY_ID" >> $GITHUB_STEP_SUMMARY

      # ---- Slack: DEPLOYMENT CREADO ----
      - name: Slack | Deployment creado
        if: always()
        continue-on-error: true
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          DEPLOY_URL="${{ steps.create_deploy.outputs.DEPLOY_URL }}"
          payload=$(jq -n \
            --arg env "${{ matrix.env }}" \
            --arg url "$DEPLOY_URL" \
            --arg sha "$SHORT_SHA" \
            '{text: ":package: *Deployment creado* `\($env)`",
              attachments:[{color:"#439FE0",
                fields:[
                  {title:"Deployment",value:"<\($url)|Ver en CodeDeploy>",short:true},
                  {title:"Commit",value:$sha,short:true}
                ]}]}')
          curl -fsS -X POST -H 'Content-type: application/json' \
            --data "$payload" "$SLACK_WEBHOOK_URL" >/dev/null

      # (CodeDeploy hace el rolling y validación en la/las EC2)

      # ---- Slack: ÉXITO ----
      - name: Slack | Éxito
        if: success()
        continue-on-error: true
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          payload=$(jq -n --arg env "${{ matrix.env }}" --arg sha "$SHORT_SHA" \
            '{text: ":white_check_mark: *Deploy OK* `\($env)` (commit \($sha))"}')
          curl -fsS -X POST -H 'Content-type: application/json' \
            --data "$payload" "$SLACK_WEBHOOK_URL" >/dev/null

      # ---- Slack: ERROR ----
      - name: Slack | Error
        if: failure()
        continue-on-error: true
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          JOB_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          payload=$(jq -n --arg env "${{ matrix.env }}" --arg sha "$SHORT_SHA" --arg url "$JOB_URL" \
            '{text: ":x: *Deploy FALLÓ* `\($env)` (commit \($sha))",
              attachments:[{color:"#E01E5A",text:"<\($url)|Ver logs del workflow>"}]}')
          curl -fsS -X POST -H 'Content-type: application/json' \
            --data "$payload" "$SLACK_WEBHOOK_URL" >/dev/null
